# Phase 7 validation: compare invoke_line_based() output against invoke() for all
# conformance test files.  Each test runs lb_compare with the same -reduce flag (if
# any) used in the original decoder conformance tests.

# ── HT Profile 0 ─────────────────────────────────────────────────────────────
add_test(NAME lb_p0_ht_01_11 COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/ds0_ht_01_b11.j2k)
add_test(NAME lb_p0_ht_02_11 COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/ds0_ht_02_b11.j2k)
add_test(NAME lb_p0_ht_03_11 COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/ds0_ht_03_b11.j2k)
add_test(NAME lb_p0_ht_03_14 COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/ds0_ht_03_b14.j2k)
add_test(NAME lb_p0_ht_04_11 COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/ds0_ht_04_b11.j2k)
add_test(NAME lb_p0_ht_04_12 COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/ds0_ht_04_b12.j2k)
add_test(NAME lb_p0_ht_05_11 COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/ds0_ht_05_b11.j2k)
add_test(NAME lb_p0_ht_05_12 COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/ds0_ht_05_b12.j2k)
add_test(NAME lb_p0_ht_06_11 COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/ds0_ht_06_b11.j2k)
add_test(NAME lb_p0_ht_06_15 COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/ds0_ht_06_b15.j2k)
add_test(NAME lb_p0_ht_06_18 COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/ds0_ht_06_b18.j2k)
add_test(NAME lb_p0_hm_06_11 COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/ds0_hm_06_b11.j2k)
add_test(NAME lb_p0_hm_06_18 COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/ds0_hm_06_b18.j2k)
add_test(NAME lb_p0_ht_07_11 COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/ds0_ht_07_b11.j2k)
add_test(NAME lb_p0_ht_07_15 COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/ds0_ht_07_b15.j2k)
add_test(NAME lb_p0_ht_07_16 COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/ds0_ht_07_b16.j2k)
add_test(NAME lb_p0_ht_08_11 COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/ds0_ht_08_b11.j2k -reduce 1)
add_test(NAME lb_p0_ht_08_15 COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/ds0_ht_08_b15.j2k -reduce 1)
add_test(NAME lb_p0_ht_08_16 COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/ds0_ht_08_b16.j2k -reduce 1)
add_test(NAME lb_p0_hm_15_8  COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/ds0_hm_15_b8.j2k)

# ── HT Profile 1 ─────────────────────────────────────────────────────────────
add_test(NAME lb_p1_ht_01_11 COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/ds1_ht_01_b11.j2k)
add_test(NAME lb_p1_ht_01_12 COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/ds1_ht_01_b12.j2k)
add_test(NAME lb_p1_ht_02_11 COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/ds1_ht_02_b11.j2k)
add_test(NAME lb_p1_ht_02_12 COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/ds1_ht_02_b12.j2k)
add_test(NAME lb_p1_ht_03_11 COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/ds1_ht_03_b11.j2k)
add_test(NAME lb_p1_ht_03_12 COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/ds1_ht_03_b12.j2k)
add_test(NAME lb_p1_ht_04_11 COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/ds1_ht_04_b11.j2k)
add_test(NAME lb_p1_ht_04_12 COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/ds1_ht_04_b12.j2k)
add_test(NAME lb_p1_ht_05_11 COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/ds1_ht_05_b11.j2k)
add_test(NAME lb_p1_ht_05_12 COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/ds1_ht_05_b12.j2k)
add_test(NAME lb_p1_ht_06_11 COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/ds1_ht_06_b11.j2k)
add_test(NAME lb_p1_ht_06_12 COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/ds1_ht_06_b12.j2k)

# ── Part 1 Profile 0 ─────────────────────────────────────────────────────────
add_test(NAME lb_p0_01  COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/p0_01.j2k)
add_test(NAME lb_p0_02  COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/p0_02.j2k)
add_test(NAME lb_p0_03  COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/p0_03.j2k)
add_test(NAME lb_p0_04  COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/p0_04.j2k)
add_test(NAME lb_p0_05  COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/p0_05.j2k)
add_test(NAME lb_p0_06  COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/p0_06.j2k)
add_test(NAME lb_p0_07  COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/p0_07.j2k)
add_test(NAME lb_p0_08  COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/p0_08.j2k -reduce 1)
add_test(NAME lb_p0_09  COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/p0_09.j2k)
add_test(NAME lb_p0_10  COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/p0_10.j2k)
add_test(NAME lb_p0_11  COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/p0_11.j2k)
add_test(NAME lb_p0_12  COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/p0_12.j2k)
add_test(NAME lb_p0_13  COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/p0_13.j2k)
add_test(NAME lb_p0_14  COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/p0_14.j2k)
add_test(NAME lb_p0_15  COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/p0_15.j2k)
add_test(NAME lb_p0_16  COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/p0_16.j2k)

# ── Part 1 Profile 1 ─────────────────────────────────────────────────────────
add_test(NAME lb_p1_01  COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/p1_01.j2k)
add_test(NAME lb_p1_02  COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/p1_02.j2k)
add_test(NAME lb_p1_03  COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/p1_03.j2k)
add_test(NAME lb_p1_04  COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/p1_04.j2k)
add_test(NAME lb_p1_05  COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/p1_05.j2k)
add_test(NAME lb_p1_06  COMMAND lb_compare ${CONFORMANCE_DATA_DIR}/p1_06.j2k)
